#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Buffer_A { float data_a[]; };
layout(std430, binding = 1) writeonly buffer Buffer_C { float data_c[]; };

layout(push_constant) uniform Relu_Dimensions {
    uint total_elements;
} dims;

void main() {
    uint elem_idx = gl_GlobalInvocationID.x;
    if (elem_idx < dims.total_elements) {
        float val = data_a[elem_idx];
        data_c[elem_idx] = max(0.0, val);
    }
}