#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Buffer_A
{
    float16_t data_a[];
};

layout(std430, binding = 1) readonly buffer Buffer_B
{
    float16_t data_b[];
};

layout(std430, binding = 2) writeonly buffer Buffer_C
{
    float16_t data_c[];
};

layout(push_constant) uniform Elementwise_Dimensions
{
    uint total_elements;
    uint cols;
    uint is_broadcast;
} dims;

void main()
{
    uint idx = gl_GlobalInvocationID.x;

    if (idx >= dims.total_elements)
        return;

    uint rhs_idx = idx;

    if (dims.is_broadcast != 0)
    {
        rhs_idx = idx % dims.cols;
    }

    data_c[idx] = data_a[idx] - data_b[rhs_idx];
}
