#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer InA { float data_a[]; };
layout(std430, binding = 1) readonly buffer InB { float data_b[]; };
layout(std430, binding = 2) writeonly buffer OutY { float data_y[]; };

layout(push_constant) uniform Constants {
    uint total_elements;
} pcs;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= pcs.total_elements) return;

    float a = data_a[idx];
    float b = data_b[idx];

    float sig_a = 1.0 / (1.0 + exp(-a));
    float silu_a = a * sig_a;

    data_y[idx] = silu_a * b;
}
