#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require

#define TILE_SIZE 16

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Buffer_A { float16_t data_a[]; };
layout(std430, binding = 1) writeonly buffer Buffer_C { float16_t data_c[]; };

layout(push_constant) uniform Transpose_Dimensions {
    uint rows;
    uint cols;
} dims;

shared float16_t tile[TILE_SIZE][TILE_SIZE + 1];

void main() {
    uint in_col = gl_GlobalInvocationID.x;
    uint in_row = gl_GlobalInvocationID.y;

    uint local_col = gl_LocalInvocationID.x;
    uint local_row = gl_LocalInvocationID.y;

    if (in_row < dims.rows && in_col < dims.cols) {
        tile[local_row][local_col] = data_a[in_row * dims.cols + in_col];
    }

    barrier();

    uint out_col = gl_WorkGroupID.y * TILE_SIZE + local_col;
    uint out_row = gl_WorkGroupID.x * TILE_SIZE + local_row;

    if (out_row < dims.cols && out_col < dims.rows) {
        data_c[out_row * dims.rows + out_col] = tile[local_col][local_row];
    }
}
