#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Buffer_A { float data_a[]; };
layout(std430, binding = 1) readonly buffer Buffer_B { float data_b[]; };
layout(std430, binding = 2) writeonly buffer Buffer_C { float data_c[]; };

layout(push_constant) uniform Elementwise_Dimensions {
    uint total_elements;
    uint cols;
    uint is_broadcast;
} dims;

void main() {
    uint elem_idx = gl_GlobalInvocationID.x;
    if (elem_idx < dims.total_elements) {
        uint b_idx = (dims.is_broadcast == 1) ? (elem_idx % dims.cols) : elem_idx;
        data_c[elem_idx] = data_a[elem_idx] - data_b[b_idx];
    }
}